### ISSUE TITLE
document relationship to interpolation changes in Scala 2.12.5

### ISSUE THREAD

**Issue by SethTisue** [outr/perfolation#1]
https://github.com/scala/scala/pull/6093 will ship as part of 2.12.5, users will want to know what's same/different here

**Comment by darkfrog26** [comment]
Once 2.12.5 is released, only the implicit classes for numeric types will still be useful.  The actual interpolation can go entirely away.

**Comment by plokhotnyuk** [comment]
I have run benchmarks with Scala 2.12.5-bin-0b6d7c3 nightly build from this branch: https://github.com/Sizmek/fast-string-interpolator/tree/try-with-scala-2.12.5-nightly-build

A throughput of simple and raw interpolators increased in ~70%, heap usage reduced in ~1.5x times (NOTE: it highly depend on payload), but there is room for improvements and results of interpolators of [perfolation](https://github.com/outr/perfolation) & [fast-string-interpolator](https://github.com/Sizmek/fast-string-interpolator) projects clearly demonstrate it.

Please see plotted benchmark results (secondary metrics can be selected in the drop-down list at top right corner, or expanded by zoom button near a title of the benchmark): https://jmh.morethan.io/?source=https://sizmek.github.io/fast-string-interpolator/jdk-8_scala-2.12.5-bin-0b6d7c3.json

**Comment by darkfrog26** [comment]
@plokhotnyuk that's really good insights.  @SethTisue, is there any possibility that we can further improve the performance before 2.12.5 gets released?

**Comment by SethTisue** [comment]
the 2.12.5 window has closed, but there will be a 2.12.6.
