### ISSUE TITLE
Looks like version in ReadMe.md needs to be updated to 1.0.4

### ISSUE THREAD

**Issue by LeeTibbert** [outr/perfolation#10]
Overall,  interesting & promising work.  Easy to follow the README.md.

A nit:  The version in  README.md (sp?) is 1.0.2. The current project version
          appears to be 1.0.4.  Clever people will figure it out, but....

Yeah, keeping versions in sync is a pain

The nit report is to give you encouragement that people actually read the README.md.

##### Background:

I hope to study the f interpolator stuff to help me figure out why Scala 2.12.6 JVM
is giving me all uppercase INFINITY.  I can't find the f interpolator code in the
scala source, miserable me, and I realize that your code probably does not
have the same bug, but it may tell me which original files to search for.
Blatant ripping off is a form of high complement ;-)
```
scala> val mPIp = math.Pi * math.pow(10.0D, 308)
mPIp: Double = Infinity

scala> println(f"pI = $mPIp%.21G")
pI = INFINITY
```

The underlying problem that I am working on is getting Scala Native
Double & Float toString to more closely emulate the Scala JVM output.
Right now those two are fixed size C printfs (%f): No exponential notation
and such.

**Comment by darkfrog26** [comment]
Thanks for pointing that out.  Let me know if there's anything I can do to help.  This project hasn't received a lot of visibility, but I think it could be a very useful ideology change as a replacement for `f` interpolation.
