### ISSUE TITLE
CrossDate is missing a DST_OFFSET-field

### ISSUE THREAD

**Issue by megri** [outr/perfolation#3]
… or maybe it's exposing too much of the underlying java.util.Calendar-interface. Working with timeZoneOffset forces me to calculate the offset hours/minutes manually (I am writing a ISO8601-formatter for scribe).

**Comment by darkfrog26** [comment]
Do you know how to get that manually?  If you don't have a chance to look into it earlier I'll try to look into it this afternoon.

**Comment by megri** [comment]
Getting the offset field is simply `def daylightSavingTimeOffset: Int = c.get(Calendar.DST_OFFSET)`
To actually get a value where DST is included if applicable you can use `c.getTimeZone.getOffset(timestamp)`.

The last offset is probably what users will want as it affects the system clock.

**Comment by darkfrog26** [comment]
@megri the other question is, how do I get it in JavaScript.  I think this is why I excluded it from CrossDate, because the availability of it in JavaScript was not easily accomplished.

**Comment by darkfrog26** [comment]
@megri are you interested in helping to make this work?

**Comment by megri** [comment]
I don't have much experience of the Javascript API, what's available and not, but I could give it a look :)

**Comment by darkfrog26** [comment]
Here's a good place to start: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by megri** [comment]
A quick peek shows that `Date.getTimezoneOffset` returns an offset that already includes DST. The easiest fix would be to make the JVM-side of things conform. That is, `timeZoneOffset` should include  the DST_OFFSET-value

**Comment by darkfrog26** [comment]
I don't have a problem with that as long as the date formatting features aren't compromised (https://github.com/outr/perfolation/blob/master/core/shared/src/main/scala/perfolation/CrossDate.scala#L37)

**Comment by darkfrog26** [comment]
https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html

**Comment by megri** [comment]
PR in #4 :)

**Comment by darkfrog26** [comment]
Awesome! Merged, and thanks.

**Comment by megri** [comment]
No problem, I am using your libraries after all ;)

**Comment by darkfrog26** [comment]
You've submitted code, so it's your library now too. :)
