### ISSUE TITLE
Master branch doesn't compile anymore

### ISSUE THREAD

**Issue by SethTisue** [outr/perfolation#49]
after 551ef9fd8015e9938b248a8a0790ea3889d0f320, `Compile/compile` passes but there are tons of compile errors with `Test/compile`, for example

```
[error] /Users/tisue/perfolation/core/shared/src/test/scala/tests/DateFormatSpec.scala:3:8: not found: object testy
[error] import testy.Spec
[error]        ^
```

this came up in the Scala 2 community build

**Comment by darkfrog26** [comment]
@SethTisue, sorry about that, this is fixed.

**Comment by SethTisue** [comment]
scala/community-build@4eb20cbcad35dbf98507989416fd2628cfbadce4 👍
