### ISSUE TITLE
Cross-platform ponderings

### ISSUE THREAD

**Issue by megri** [outr/perfolation#5]
I just noticed that the timezone-offset for JS is counted in minutes, while the JVM uses milliseconds.

references
* js: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset
* jvm: https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html#ZONE_OFFSET

In short: the same code will give different values depending on platform.

**Comment by megri** [comment]
I also noticed that methods defined on scala-native java.util.Calendar are merely stubs. They throw exceptions when used. :(

**Comment by darkfrog26** [comment]
That's not good.  Do you know if the Java8 variant works?

**Comment by megri** [comment]
Nope, the java.time-implementation only contains Instant, and a very simple stub at that. If you want it to work for scala-native the best bet would be to reimplement those parts with the C-library bindings scala-native provides.

**Comment by megri** [comment]
Btw, I'm thinking the timezone should be formatted according to http://man7.org/linux/man-pages/man3/strftime.3.html, that is in a +/-hhmm format. This would be pretty simple to implement for both JVM and JS

**Comment by megri** [comment]
... of course, [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) dictates that the timezone should be formatted like +/-hh:mm (mind the colon), so maybe the hh and mm timezone parts should be accessible as separate entities

**Comment by darkfrog26** [comment]
That's a good point.  Any chance you're interested in tackling this?

**Comment by megri** [comment]
Sure, I'll give it a go

**Comment by darkfrog26** [comment]
Can I close this ticket?

**Comment by megri** [comment]
Yes I believe it was resolved with #6

**Comment by megri** [comment]
... well, the cross platform issues regarding java.util.Calendar in native/js are still there.

**Comment by darkfrog26** [comment]
@megri can you clarify?

**Comment by megri** [comment]
(sorry, haven't had my mind on this for a while.)

Things that was resolved:
* All implementations expose milliseconds;
* Minutes and hours was exposed;
* The formatting of those two in the `z` alias should be ok-ish

Things still not resolved:
* Runtime errors on native (and possibly js) due to missing implementations of the java.*-APIs.

**Comment by darkfrog26** [comment]
This should only be an issue for Native as I don't have any active projects I'm using it in.  Scala.js I used constantly and it works perfectly well.  I'll have to try to get ScalaTest to work with ScalaNative.

**Comment by darkfrog26** [comment]
Looks like I can only test with ScalaTest on 3.2.0-SNAP10

**Comment by darkfrog26** [comment]
We appear to be stuck on ScalaNative support waiting for this: https://github.com/scala-native/scala-native/issues/987

**Comment by darkfrog26** [comment]
Would anyone have a problem with Moment.js (http://momentjs.com/) being incorporated as a dependency for the Scala.js implementation?  This would allow much better integration, and the dependency isn't incredibly large.

**Comment by megri** [comment]
There's also https://github.com/cquiroz/scala-java-time which, I believe, implements the full java8-time api. I always mix it up with the similarly named https://github.com/scala-js/scala-js-java-time. One of them is incomplete; I think the latter one.

**Comment by darkfrog26** [comment]
@megri, we were previously using that and much of what we're trying to resolve is getting rid of it as a dependency.  The JS size increase was massive when using it.

**Comment by megri** [comment]
I see. While I don't have anything against moment.js in particular, I'm always wary about pulling in foreign JS-dependencies that can conflict with user-defined ones. If moment.js is well-contained and doesn't rely on any global configuration I don't see a problem.

**Comment by darkfrog26** [comment]
I'm considering just creating our own pure Scala mapping of timezone data to make this a bit more pure and type-safe.

**Comment by darkfrog26** [comment]
@megri, can you confirm this is no longer a problem?

**Comment by megri** [comment]
@darkfrog26 Sorry, been out of the loop for a while and haven't experimented with native for a while. I'd say close the issue for now and reference it if a ticket is filed in the future.

**Comment by darkfrog26** [comment]
@megri will do. I think it should be working properly now.
