### ISSUE TITLE
Benefits vs Costs of NumberFormat caching

### ISSUE THREAD

**Issue by RafalSumislawski** [outr/perfolation#7]
Hi
I've noticed perfolation is caching `NumberFormat` instances in `NumberFormatUtil` and that this process includes acquiring an application wide lock. In case of highly-concurrent, string-formatting-heavy application the `synchronised` will quickly became a bottleneck, even if it doesn't it may be very CPU expensive.

Originally I wanted to propose a lock-free implementation of the cache, but I started to analyse whether the cache is beneficial at all. I know of two good reasons to cache objects: reducing allocation rate to give a break to the GC or avoiding cost of CPU expensive initialisation.

In this case it surely doesn't reduce allocations, because it avoids allocation of a `NumberFormat` (which is 48 bytes on my machine) at the expense of allocating the `key: String` (which is 96 bytes on my machine + whatever is allocated in the process of creating that string).

Regarding CPU cost of NumberFormat allocation: The 
```
      nf.setGroupingUsed(g)
      c.foreach(nf.setCurrency)
      nf.setMaximumFractionDigits(maxF)
      nf.setMinimumFractionDigits(f)
      nf.setMaximumIntegerDigits(maxI)
      nf.setMinimumIntegerDigits(i)
      nf.setParseIntegerOnly(maxF == 0)
      nf.setRoundingMode(rm)
```
seems pretty cheap, as these methods aren't doing much more than just setting some fields.
The only code that MAY actually cost a significant number of CPU cycles is `NumberFormat.getInstance()`.

So, as far as I can see, one could avoid: allocating any temporary garbage, the cost of building the `key`, the cost of `synchronised`, and the cost of `NumberFormat.getInstance()` by using a `ThreadLocal[NumberFormat]` and configuring it before each use.

**Comment by darkfrog26** [comment]
Interested in writing a PR to resolve this? :)

**Comment by RafalSumislawski** [comment]
I am. (once I'm done fighting with scala-native on Windows xD)

**Comment by darkfrog26** [comment]
Merged both PRs.  I appreciate the contributions! Thanks.

**Comment by RafalSumislawski** [comment]
No Problem :)
